---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "controller01"
  os:
    name: "ubuntu"
    release: "focal"
  networks:
    - name: public-net
      ip: "10.10.16.3"
  memory: 16384
  cpus: 4
  roles:
    - kube-master
    - etcd
  volumes:
    - name: sda
      size: 80
      mount: /var/lib/docker/
- name: "controller02"
  os:
    name: "ubuntu"
    release: "focal"
  networks:
    - name: public-net
      ip: "10.10.16.4"   
  memory: 16384
  cpus: 4
  roles:
    - kube-master
    - etcd
  volumes:
    - name: sda
      size: 80
      mount: /var/lib/docker/
- name: "controller03"
  os:
    name: "ubuntu"
    release: "focal"
  networks:
    - name: public-net
      ip: "10.10.16.5"
  memory: 16384
  cpus: 4
  roles:
    - kube-master
    - etcd
  volumes:
    - name: sda
      size: 80
      mount: /var/lib/docker/    
